Save states need the Simulator called first in order to function; Update to 1_aer_provider.ipynb
Save simulator states need to be called after the Simulator in order to function. Otherwise the tutorial will output a "AttributeError: 'QuantumCircuit' object has no attribute 'save_state'" error. This issue affects all save simulator states in the tutorial, so the save states were moved underneath the Simulator in each example.